/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.synbox.model.CloudServerCreateDTOEnvs;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.synbox.invoker.JSON;

/**
 * DTO for creating a new cloud server container
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-19T21:02:15.291689248Z[Etc/UTC]", comments = "Generator version: 7.22.0-SNAPSHOT")
public class CloudServerCreateDTO {
  /**
   * Power level configuration for the server
   */
  @JsonAdapter(PowerLevelEnum.Adapter.class)
  public enum PowerLevelEnum {
    SMALL_COMPUTE("SMALL_COMPUTE"),
    
    MEDIUM_COMPUTE("MEDIUM_COMPUTE"),
    
    LARGE_COMPUTE("LARGE_COMPUTE"),
    
    HEAVY_COMPUTE("HEAVY_COMPUTE"),
    
    HYTALE_FREE("HYTALE_FREE"),
    
    SMALL_RAM("SMALL_RAM"),
    
    MEDIUM_RAM("MEDIUM_RAM"),
    
    LARGE_RAM("LARGE_RAM"),
    
    SMALL_PREMIUM("SMALL_PREMIUM"),
    
    MEDIUM_PREMIUM("MEDIUM_PREMIUM");

    private String value;

    PowerLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PowerLevelEnum fromValue(String value) {
      for (PowerLevelEnum b : PowerLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PowerLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PowerLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PowerLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PowerLevelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PowerLevelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_POWER_LEVEL = "powerLevel";
  @SerializedName(SERIALIZED_NAME_POWER_LEVEL)
  @jakarta.annotation.Nonnull
  private PowerLevelEnum powerLevel;

  public static final String SERIALIZED_NAME_START_VOLUME = "startVolume";
  @SerializedName(SERIALIZED_NAME_START_VOLUME)
  @jakarta.annotation.Nullable
  private String startVolume;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @jakarta.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_ENVS = "envs";
  @SerializedName(SERIALIZED_NAME_ENVS)
  @jakarta.annotation.Nullable
  private CloudServerCreateDTOEnvs envs;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  @jakarta.annotation.Nullable
  private String start;

  public static final String SERIALIZED_NAME_STOP = "stop";
  @SerializedName(SERIALIZED_NAME_STOP)
  @jakarta.annotation.Nullable
  private String stop;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @jakarta.annotation.Nonnull
  private String displayName;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  @jakarta.annotation.Nullable
  private String organization;

  public static final String SERIALIZED_NAME_ENABLE_AUTO_POWER_CONTROL = "enableAutoPowerControl";
  @SerializedName(SERIALIZED_NAME_ENABLE_AUTO_POWER_CONTROL)
  @jakarta.annotation.Nullable
  private Boolean enableAutoPowerControl = true;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  @jakarta.annotation.Nullable
  private List<String> volumes = new ArrayList<>();

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @jakarta.annotation.Nullable
  private String accountId;

  public CloudServerCreateDTO() {
  }

  public CloudServerCreateDTO powerLevel(@jakarta.annotation.Nonnull PowerLevelEnum powerLevel) {
    this.powerLevel = powerLevel;
    return this;
  }

  /**
   * Power level configuration for the server
   * @return powerLevel
   */
  @jakarta.annotation.Nonnull
  public PowerLevelEnum getPowerLevel() {
    return powerLevel;
  }

  public void setPowerLevel(@jakarta.annotation.Nonnull PowerLevelEnum powerLevel) {
    this.powerLevel = powerLevel;
  }


  public CloudServerCreateDTO startVolume(@jakarta.annotation.Nullable String startVolume) {
    this.startVolume = startVolume;
    return this;
  }

  /**
   * Start volume name for the server
   * @return startVolume
   */
  @jakarta.annotation.Nullable
  public String getStartVolume() {
    return startVolume;
  }

  public void setStartVolume(@jakarta.annotation.Nullable String startVolume) {
    this.startVolume = startVolume;
  }


  public CloudServerCreateDTO provider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Provider identifier
   * @return provider
   */
  @jakarta.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public CloudServerCreateDTO envs(@jakarta.annotation.Nullable CloudServerCreateDTOEnvs envs) {
    this.envs = envs;
    return this;
  }

  /**
   * Get envs
   * @return envs
   */
  @jakarta.annotation.Nullable
  public CloudServerCreateDTOEnvs getEnvs() {
    return envs;
  }

  public void setEnvs(@jakarta.annotation.Nullable CloudServerCreateDTOEnvs envs) {
    this.envs = envs;
  }


  public CloudServerCreateDTO start(@jakarta.annotation.Nullable String start) {
    this.start = start;
    return this;
  }

  /**
   * Start time for auto power control (HH:mm format)
   * @return start
   */
  @jakarta.annotation.Nullable
  public String getStart() {
    return start;
  }

  public void setStart(@jakarta.annotation.Nullable String start) {
    this.start = start;
  }


  public CloudServerCreateDTO stop(@jakarta.annotation.Nullable String stop) {
    this.stop = stop;
    return this;
  }

  /**
   * Stop time for auto power control (HH:mm format)
   * @return stop
   */
  @jakarta.annotation.Nullable
  public String getStop() {
    return stop;
  }

  public void setStop(@jakarta.annotation.Nullable String stop) {
    this.stop = stop;
  }


  public CloudServerCreateDTO displayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Display name for the server
   * @return displayName
   */
  @jakarta.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }


  public CloudServerCreateDTO organization(@jakarta.annotation.Nullable String organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Organization ID to assign the server to (optional)
   * @return organization
   */
  @jakarta.annotation.Nullable
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(@jakarta.annotation.Nullable String organization) {
    this.organization = organization;
  }


  public CloudServerCreateDTO enableAutoPowerControl(@jakarta.annotation.Nullable Boolean enableAutoPowerControl) {
    this.enableAutoPowerControl = enableAutoPowerControl;
    return this;
  }

  /**
   * Enable automatic power control
   * @return enableAutoPowerControl
   */
  @jakarta.annotation.Nullable
  public Boolean getEnableAutoPowerControl() {
    return enableAutoPowerControl;
  }

  public void setEnableAutoPowerControl(@jakarta.annotation.Nullable Boolean enableAutoPowerControl) {
    this.enableAutoPowerControl = enableAutoPowerControl;
  }


  public CloudServerCreateDTO volumes(@jakarta.annotation.Nullable List<String> volumes) {
    this.volumes = volumes;
    return this;
  }

  public CloudServerCreateDTO addVolumesItem(String volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

  /**
   * List of volume names to attach (optional)
   * @return volumes
   */
  @jakarta.annotation.Nullable
  public List<String> getVolumes() {
    return volumes;
  }

  public void setVolumes(@jakarta.annotation.Nullable List<String> volumes) {
    this.volumes = volumes;
  }


  public CloudServerCreateDTO accountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Account ID (optional, usually auto-assigned)
   * @return accountId
   */
  @jakarta.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudServerCreateDTO cloudServerCreateDTO = (CloudServerCreateDTO) o;
    return Objects.equals(this.powerLevel, cloudServerCreateDTO.powerLevel) &&
        Objects.equals(this.startVolume, cloudServerCreateDTO.startVolume) &&
        Objects.equals(this.provider, cloudServerCreateDTO.provider) &&
        Objects.equals(this.envs, cloudServerCreateDTO.envs) &&
        Objects.equals(this.start, cloudServerCreateDTO.start) &&
        Objects.equals(this.stop, cloudServerCreateDTO.stop) &&
        Objects.equals(this.displayName, cloudServerCreateDTO.displayName) &&
        Objects.equals(this.organization, cloudServerCreateDTO.organization) &&
        Objects.equals(this.enableAutoPowerControl, cloudServerCreateDTO.enableAutoPowerControl) &&
        Objects.equals(this.volumes, cloudServerCreateDTO.volumes) &&
        Objects.equals(this.accountId, cloudServerCreateDTO.accountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(powerLevel, startVolume, provider, envs, start, stop, displayName, organization, enableAutoPowerControl, volumes, accountId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudServerCreateDTO {\n");
    sb.append("    powerLevel: ").append(toIndentedString(powerLevel)).append("\n");
    sb.append("    startVolume: ").append(toIndentedString(startVolume)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    envs: ").append(toIndentedString(envs)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    enableAutoPowerControl: ").append(toIndentedString(enableAutoPowerControl)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("powerLevel", "startVolume", "provider", "envs", "start", "stop", "displayName", "organization", "enableAutoPowerControl", "volumes", "account_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("powerLevel", "displayName"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CloudServerCreateDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CloudServerCreateDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CloudServerCreateDTO is not found in the empty JSON string", CloudServerCreateDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CloudServerCreateDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CloudServerCreateDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CloudServerCreateDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("powerLevel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `powerLevel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("powerLevel").toString()));
      }
      // validate the required field `powerLevel`
      PowerLevelEnum.validateJsonElement(jsonObj.get("powerLevel"));
      if ((jsonObj.get("startVolume") != null && !jsonObj.get("startVolume").isJsonNull()) && !jsonObj.get("startVolume").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `startVolume` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startVolume").toString()));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("start") != null && !jsonObj.get("start").isJsonNull()) && !jsonObj.get("start").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `start` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start").toString()));
      }
      if ((jsonObj.get("stop") != null && !jsonObj.get("stop").isJsonNull()) && !jsonObj.get("stop").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stop` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stop").toString()));
      }
      if (!jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("organization") != null && !jsonObj.get("organization").isJsonNull()) && !jsonObj.get("organization").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `organization` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("volumes") != null && !jsonObj.get("volumes").isJsonNull() && !jsonObj.get("volumes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `volumes` to be an array in the JSON string but got `%s`", jsonObj.get("volumes").toString()));
      }
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CloudServerCreateDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CloudServerCreateDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CloudServerCreateDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CloudServerCreateDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<CloudServerCreateDTO>() {
           @Override
           public void write(JsonWriter out, CloudServerCreateDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CloudServerCreateDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CloudServerCreateDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CloudServerCreateDTO
   * @throws IOException if the JSON string is invalid with respect to CloudServerCreateDTO
   */
  public static CloudServerCreateDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CloudServerCreateDTO.class);
  }

  /**
   * Convert an instance of CloudServerCreateDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

