/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.synbox.model.AiChatEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.synbox.invoker.JSON;

/**
 * One persisted user message or approval decision and its assistant response
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-08T14:41:04.758682586Z[Etc/UTC]", comments = "Generator version: 7.22.0-SNAPSHOT")
public class HistoryTurn {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @jakarta.annotation.Nullable
  private UUID requestId;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @jakarta.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @jakarta.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_SERVER = "server";
  @SerializedName(SERIALIZED_NAME_SERVER)
  @jakarta.annotation.Nullable
  private String server;

  public static final String SERIALIZED_NAME_APPROVAL_ID = "approvalId";
  @SerializedName(SERIALIZED_NAME_APPROVAL_ID)
  @jakarta.annotation.Nullable
  private String approvalId;

  public static final String SERIALIZED_NAME_ANSWER = "answer";
  @SerializedName(SERIALIZED_NAME_ANSWER)
  @jakarta.annotation.Nullable
  private String answer;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @jakarta.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_FINISHED_AT = "finishedAt";
  @SerializedName(SERIALIZED_NAME_FINISHED_AT)
  @jakarta.annotation.Nullable
  private OffsetDateTime finishedAt;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @jakarta.annotation.Nullable
  private List<AiChatEvent> events = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  @jakarta.annotation.Nullable
  private String errorCode;

  public HistoryTurn() {
  }

  public HistoryTurn id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Server turn id
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public HistoryTurn requestId(@jakarta.annotation.Nullable UUID requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Client request id
   * @return requestId
   */
  @jakarta.annotation.Nullable
  public UUID getRequestId() {
    return requestId;
  }

  public void setRequestId(@jakarta.annotation.Nullable UUID requestId) {
    this.requestId = requestId;
  }


  public HistoryTurn type(@jakarta.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * chat, confirm or reject
   * @return type
   */
  @jakarta.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }


  public HistoryTurn message(@jakarta.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Original user text
   * @return message
   */
  @jakarta.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public HistoryTurn server(@jakarta.annotation.Nullable String server) {
    this.server = server;
    return this;
  }

  /**
   * Selected server
   * @return server
   */
  @jakarta.annotation.Nullable
  public String getServer() {
    return server;
  }

  public void setServer(@jakarta.annotation.Nullable String server) {
    this.server = server;
  }


  public HistoryTurn approvalId(@jakarta.annotation.Nullable String approvalId) {
    this.approvalId = approvalId;
    return this;
  }

  /**
   * Approval decision target
   * @return approvalId
   */
  @jakarta.annotation.Nullable
  public String getApprovalId() {
    return approvalId;
  }

  public void setApprovalId(@jakarta.annotation.Nullable String approvalId) {
    this.approvalId = approvalId;
  }


  public HistoryTurn answer(@jakarta.annotation.Nullable String answer) {
    this.answer = answer;
    return this;
  }

  /**
   * Assistant text, possibly partial on failure
   * @return answer
   */
  @jakarta.annotation.Nullable
  public String getAnswer() {
    return answer;
  }

  public void setAnswer(@jakarta.annotation.Nullable String answer) {
    this.answer = answer;
  }


  public HistoryTurn status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * processing, completed, failed or interrupted
   * @return status
   */
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public HistoryTurn createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Start time
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public HistoryTurn finishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
    return this;
  }

  /**
   * Finish time
   * @return finishedAt
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getFinishedAt() {
    return finishedAt;
  }

  public void setFinishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
  }


  public HistoryTurn events(@jakarta.annotation.Nullable List<AiChatEvent> events) {
    this.events = events;
    return this;
  }

  public HistoryTurn addEventsItem(AiChatEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Tool lifecycle and approval events; no text deltas
   * @return events
   */
  @jakarta.annotation.Nullable
  public List<AiChatEvent> getEvents() {
    return events;
  }

  public void setEvents(@jakarta.annotation.Nullable List<AiChatEvent> events) {
    this.events = events;
  }


  public HistoryTurn errorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Failure code if present
   * @return errorCode
   */
  @jakarta.annotation.Nullable
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryTurn historyTurn = (HistoryTurn) o;
    return Objects.equals(this.id, historyTurn.id) &&
        Objects.equals(this.requestId, historyTurn.requestId) &&
        Objects.equals(this.type, historyTurn.type) &&
        Objects.equals(this.message, historyTurn.message) &&
        Objects.equals(this.server, historyTurn.server) &&
        Objects.equals(this.approvalId, historyTurn.approvalId) &&
        Objects.equals(this.answer, historyTurn.answer) &&
        Objects.equals(this.status, historyTurn.status) &&
        Objects.equals(this.createdAt, historyTurn.createdAt) &&
        Objects.equals(this.finishedAt, historyTurn.finishedAt) &&
        Objects.equals(this.events, historyTurn.events) &&
        Objects.equals(this.errorCode, historyTurn.errorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, requestId, type, message, server, approvalId, answer, status, createdAt, finishedAt, events, errorCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryTurn {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    approvalId: ").append(toIndentedString(approvalId)).append("\n");
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "requestId", "type", "message", "server", "approvalId", "answer", "status", "createdAt", "finishedAt", "events", "errorCode"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HistoryTurn
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HistoryTurn.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HistoryTurn is not found in the empty JSON string", HistoryTurn.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HistoryTurn.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HistoryTurn` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("requestId") != null && !jsonObj.get("requestId").isJsonNull()) && !jsonObj.get("requestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `requestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestId").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("server") != null && !jsonObj.get("server").isJsonNull()) && !jsonObj.get("server").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `server` to be a primitive type in the JSON string but got `%s`", jsonObj.get("server").toString()));
      }
      if ((jsonObj.get("approvalId") != null && !jsonObj.get("approvalId").isJsonNull()) && !jsonObj.get("approvalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `approvalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("approvalId").toString()));
      }
      if ((jsonObj.get("answer") != null && !jsonObj.get("answer").isJsonNull()) && !jsonObj.get("answer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `answer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("answer").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (jsonObj.get("events") != null && !jsonObj.get("events").isJsonNull()) {
        JsonArray jsonArrayevents = jsonObj.getAsJsonArray("events");
        if (jsonArrayevents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("events").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
          }

          // validate the optional field `events` (array)
          for (int i = 0; i < jsonArrayevents.size(); i++) {
            AiChatEvent.validateJsonElement(jsonArrayevents.get(i));
          };
        }
      }
      if ((jsonObj.get("errorCode") != null && !jsonObj.get("errorCode").isJsonNull()) && !jsonObj.get("errorCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HistoryTurn.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HistoryTurn' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HistoryTurn> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HistoryTurn.class));

       return (TypeAdapter<T>) new TypeAdapter<HistoryTurn>() {
           @Override
           public void write(JsonWriter out, HistoryTurn value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HistoryTurn read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HistoryTurn given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HistoryTurn
   * @throws IOException if the JSON string is invalid with respect to HistoryTurn
   */
  public static HistoryTurn fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HistoryTurn.class);
  }

  /**
   * Convert an instance of HistoryTurn to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

