/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.synbox.invoker.JSON;

/**
 * VPSModel
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-09T17:05:38.143220079Z[Etc/UTC]", comments = "Generator version: 7.22.0-SNAPSHOT")
public class VPSModel {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @jakarta.annotation.Nullable
  private String accountId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_IPV4 = "ipv4";
  @SerializedName(SERIALIZED_NAME_IPV4)
  @jakarta.annotation.Nullable
  private String ipv4;

  public static final String SERIALIZED_NAME_IPV6 = "ipv6";
  @SerializedName(SERIALIZED_NAME_IPV6)
  @jakarta.annotation.Nullable
  private String ipv6;

  public static final String SERIALIZED_NAME_CPU = "cpu";
  @SerializedName(SERIALIZED_NAME_CPU)
  @jakarta.annotation.Nullable
  private Integer cpu;

  public static final String SERIALIZED_NAME_RAM = "ram";
  @SerializedName(SERIALIZED_NAME_RAM)
  @jakarta.annotation.Nullable
  private Integer ram;

  public static final String SERIALIZED_NAME_STORAGE = "storage";
  @SerializedName(SERIALIZED_NAME_STORAGE)
  @jakarta.annotation.Nullable
  private Long storage;

  public static final String SERIALIZED_NAME_EXPIRES = "expires";
  @SerializedName(SERIALIZED_NAME_EXPIRES)
  @jakarta.annotation.Nullable
  private Long expires;

  public static final String SERIALIZED_NAME_BACKUP_SLOTS = "backupSlots";
  @SerializedName(SERIALIZED_NAME_BACKUP_SLOTS)
  @jakarta.annotation.Nullable
  private Integer backupSlots;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @jakarta.annotation.Nullable
  private Double price;

  public static final String SERIALIZED_NAME_HOURLY = "hourly";
  @SerializedName(SERIALIZED_NAME_HOURLY)
  @jakarta.annotation.Nullable
  private Boolean hourly;

  public VPSModel() {
  }

  public VPSModel id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public VPSModel accountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @jakarta.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public VPSModel name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public VPSModel ipv4(@jakarta.annotation.Nullable String ipv4) {
    this.ipv4 = ipv4;
    return this;
  }

  /**
   * Get ipv4
   * @return ipv4
   */
  @jakarta.annotation.Nullable
  public String getIpv4() {
    return ipv4;
  }

  public void setIpv4(@jakarta.annotation.Nullable String ipv4) {
    this.ipv4 = ipv4;
  }


  public VPSModel ipv6(@jakarta.annotation.Nullable String ipv6) {
    this.ipv6 = ipv6;
    return this;
  }

  /**
   * Get ipv6
   * @return ipv6
   */
  @jakarta.annotation.Nullable
  public String getIpv6() {
    return ipv6;
  }

  public void setIpv6(@jakarta.annotation.Nullable String ipv6) {
    this.ipv6 = ipv6;
  }


  public VPSModel cpu(@jakarta.annotation.Nullable Integer cpu) {
    this.cpu = cpu;
    return this;
  }

  /**
   * Get cpu
   * @return cpu
   */
  @jakarta.annotation.Nullable
  public Integer getCpu() {
    return cpu;
  }

  public void setCpu(@jakarta.annotation.Nullable Integer cpu) {
    this.cpu = cpu;
  }


  public VPSModel ram(@jakarta.annotation.Nullable Integer ram) {
    this.ram = ram;
    return this;
  }

  /**
   * Get ram
   * @return ram
   */
  @jakarta.annotation.Nullable
  public Integer getRam() {
    return ram;
  }

  public void setRam(@jakarta.annotation.Nullable Integer ram) {
    this.ram = ram;
  }


  public VPSModel storage(@jakarta.annotation.Nullable Long storage) {
    this.storage = storage;
    return this;
  }

  /**
   * Get storage
   * @return storage
   */
  @jakarta.annotation.Nullable
  public Long getStorage() {
    return storage;
  }

  public void setStorage(@jakarta.annotation.Nullable Long storage) {
    this.storage = storage;
  }


  public VPSModel expires(@jakarta.annotation.Nullable Long expires) {
    this.expires = expires;
    return this;
  }

  /**
   * Get expires
   * @return expires
   */
  @jakarta.annotation.Nullable
  public Long getExpires() {
    return expires;
  }

  public void setExpires(@jakarta.annotation.Nullable Long expires) {
    this.expires = expires;
  }


  public VPSModel backupSlots(@jakarta.annotation.Nullable Integer backupSlots) {
    this.backupSlots = backupSlots;
    return this;
  }

  /**
   * Get backupSlots
   * @return backupSlots
   */
  @jakarta.annotation.Nullable
  public Integer getBackupSlots() {
    return backupSlots;
  }

  public void setBackupSlots(@jakarta.annotation.Nullable Integer backupSlots) {
    this.backupSlots = backupSlots;
  }


  public VPSModel price(@jakarta.annotation.Nullable Double price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @jakarta.annotation.Nullable
  public Double getPrice() {
    return price;
  }

  public void setPrice(@jakarta.annotation.Nullable Double price) {
    this.price = price;
  }


  public VPSModel hourly(@jakarta.annotation.Nullable Boolean hourly) {
    this.hourly = hourly;
    return this;
  }

  /**
   * Get hourly
   * @return hourly
   */
  @jakarta.annotation.Nullable
  public Boolean getHourly() {
    return hourly;
  }

  public void setHourly(@jakarta.annotation.Nullable Boolean hourly) {
    this.hourly = hourly;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VPSModel vpSModel = (VPSModel) o;
    return Objects.equals(this.id, vpSModel.id) &&
        Objects.equals(this.accountId, vpSModel.accountId) &&
        Objects.equals(this.name, vpSModel.name) &&
        Objects.equals(this.ipv4, vpSModel.ipv4) &&
        Objects.equals(this.ipv6, vpSModel.ipv6) &&
        Objects.equals(this.cpu, vpSModel.cpu) &&
        Objects.equals(this.ram, vpSModel.ram) &&
        Objects.equals(this.storage, vpSModel.storage) &&
        Objects.equals(this.expires, vpSModel.expires) &&
        Objects.equals(this.backupSlots, vpSModel.backupSlots) &&
        Objects.equals(this.price, vpSModel.price) &&
        Objects.equals(this.hourly, vpSModel.hourly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountId, name, ipv4, ipv6, cpu, ram, storage, expires, backupSlots, price, hourly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VPSModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ipv4: ").append(toIndentedString(ipv4)).append("\n");
    sb.append("    ipv6: ").append(toIndentedString(ipv6)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    ram: ").append(toIndentedString(ram)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    backupSlots: ").append(toIndentedString(backupSlots)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    hourly: ").append(toIndentedString(hourly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "accountId", "name", "ipv4", "ipv6", "cpu", "ram", "storage", "expires", "backupSlots", "price", "hourly"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VPSModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VPSModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in VPSModel is not found in the empty JSON string", VPSModel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VPSModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `VPSModel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("accountId") != null && !jsonObj.get("accountId").isJsonNull()) && !jsonObj.get("accountId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `accountId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("ipv4") != null && !jsonObj.get("ipv4").isJsonNull()) && !jsonObj.get("ipv4").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ipv4` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipv4").toString()));
      }
      if ((jsonObj.get("ipv6") != null && !jsonObj.get("ipv6").isJsonNull()) && !jsonObj.get("ipv6").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ipv6` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipv6").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VPSModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VPSModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VPSModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VPSModel.class));

       return (TypeAdapter<T>) new TypeAdapter<VPSModel>() {
           @Override
           public void write(JsonWriter out, VPSModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VPSModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VPSModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VPSModel
   * @throws IOException if the JSON string is invalid with respect to VPSModel
   */
  public static VPSModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VPSModel.class);
  }

  /**
   * Convert an instance of VPSModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

