/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.synbox.model.BackupModel;
import de.synbox.model.CloudServerModelEnvs;
import de.synbox.model.ContainerProvider;
import de.synbox.model.Document;
import de.synbox.model.ScheduleModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CloudServerModel
 */
public class CloudServerModelTest {
    private final CloudServerModel model = new CloudServerModel();

    /**
     * Model tests for CloudServerModel
     */
    @Test
    public void testCloudServerModel() {
        // TODO: test CloudServerModel
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'stop'
     */
    @Test
    public void stopTest() {
        // TODO: test stop
    }

    /**
     * Test the property 'enableAutoPowerControl'
     */
    @Test
    public void enableAutoPowerControlTest() {
        // TODO: test enableAutoPowerControl
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'suspended'
     */
    @Test
    public void suspendedTest() {
        // TODO: test suspended
    }

    /**
     * Test the property 'cpuType'
     */
    @Test
    public void cpuTypeTest() {
        // TODO: test cpuType
    }

    /**
     * Test the property 'powerLevel'
     */
    @Test
    public void powerLevelTest() {
        // TODO: test powerLevel
    }

    /**
     * Test the property 'scheduleModels'
     */
    @Test
    public void scheduleModelsTest() {
        // TODO: test scheduleModels
    }

    /**
     * Test the property 'backups'
     */
    @Test
    public void backupsTest() {
        // TODO: test backups
    }

    /**
     * Test the property 'watching'
     */
    @Test
    public void watchingTest() {
        // TODO: test watching
    }

    /**
     * Test the property 'startVolume'
     */
    @Test
    public void startVolumeTest() {
        // TODO: test startVolume
    }

    /**
     * Test the property 'serverId'
     */
    @Test
    public void serverIdTest() {
        // TODO: test serverId
    }

    /**
     * Test the property 'moneyPoolId'
     */
    @Test
    public void moneyPoolIdTest() {
        // TODO: test moneyPoolId
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

    /**
     * Test the property 'envs'
     */
    @Test
    public void envsTest() {
        // TODO: test envs
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'publicIp'
     */
    @Test
    public void publicIpTest() {
        // TODO: test publicIp
    }

    /**
     * Test the property 'oneTmePassword'
     */
    @Test
    public void oneTmePasswordTest() {
        // TODO: test oneTmePassword
    }

    /**
     * Test the property 'containerProvider'
     */
    @Test
    public void containerProviderTest() {
        // TODO: test containerProvider
    }

    /**
     * Test the property 'deltaTillStart'
     */
    @Test
    public void deltaTillStartTest() {
        // TODO: test deltaTillStart
    }

}
