/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1FileKeySelector
 */
public class V1FileKeySelectorTest {
    private final V1FileKeySelector model = new V1FileKeySelector();

    /**
     * Model tests for V1FileKeySelector
     */
    @Test
    public void testV1FileKeySelector() {
        // TODO: test V1FileKeySelector
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'optional'
     */
    @Test
    public void optionalTest() {
        // TODO: test optional
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'volumeName'
     */
    @Test
    public void volumeNameTest() {
        // TODO: test volumeName
    }

}
