/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.synbox.model.Quantity;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1ResourceFieldSelector
 */
public class V1ResourceFieldSelectorTest {
    private final V1ResourceFieldSelector model = new V1ResourceFieldSelector();

    /**
     * Model tests for V1ResourceFieldSelector
     */
    @Test
    public void testV1ResourceFieldSelector() {
        // TODO: test V1ResourceFieldSelector
    }

    /**
     * Test the property 'containerName'
     */
    @Test
    public void containerNameTest() {
        // TODO: test containerName
    }

    /**
     * Test the property 'divisor'
     */
    @Test
    public void divisorTest() {
        // TODO: test divisor
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

}
