/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BackupManagementApi
 */
@Disabled
public class BackupManagementApiTest {

    private final BackupManagementApi api = new BackupManagementApi();

    /**
     * Backup erstellen
     *
     * Erstellt ein neues Backup eines bestimmten Volumes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void backupContainerTest() throws ApiException {
        String id = null;
        String volume = null;
        String response = api.backupContainer(id, volume);
        // TODO: test validations
    }

    /**
     * Backup löschen
     *
     * Löscht ein vorhandenes Backup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBackupTest() throws ApiException {
        String backupId = null;
        String id = null;
        Object response = api.deleteBackup(backupId, id);
        // TODO: test validations
    }

    /**
     * Backup herunterladen
     *
     * Lädt ein Backup als ZIP-Datei herunter
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadBackUpTest() throws ApiException {
        String id = null;
        String downloadId = null;
        api.downloadBackUp(id, downloadId);
        // TODO: test validations
    }

    /**
     * Alle Backups auflisten
     *
     * Gibt eine Liste aller verfügbaren Backups für einen Server zurück
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllBackupsTest() throws ApiException {
        String id = null;
        api.listAllBackups(id);
        // TODO: test validations
    }

    /**
     * Backup-Download anfordern
     *
     * Generiert eine temporäre Download-ID für den Zugriff auf ein bestimmtes Backup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestBackupTest() throws ApiException {
        String id = null;
        String backupId = null;
        String response = api.requestBackup(id, backupId);
        // TODO: test validations
    }

    /**
     * Backup wiederherstellen
     *
     * Stellt ein Backup auf einem bestimmten Volume wieder her
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restoreBackupTest() throws ApiException {
        String id = null;
        String backupid = null;
        String volumeReplace = null;
        String response = api.restoreBackup(id, backupid, volumeReplace);
        // TODO: test validations
    }

}
