/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CloudServerStatusWebhookControllerApi
 */
@Disabled
public class CloudServerStatusWebhookControllerApiTest {

    private final CloudServerStatusWebhookControllerApi api = new CloudServerStatusWebhookControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void receive1Test() throws ApiException {
        String body = null;
        api.receive1(body);
        // TODO: test validations
    }

}
