/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NameManagementApi
 */
@Disabled
public class NameManagementApiTest {

    private final NameManagementApi api = new NameManagementApi();

    /**
     * Change server name
     *
     * Changes the name of a specific server.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changeVersion1Test() throws ApiException {
        String serverId = null;
        String body = null;
        Object response = api.changeVersion1(serverId, body);
        // TODO: test validations
    }

}
