/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.synbox.model.BackupModel;
import de.synbox.model.CloudServerModelEnvs;
import de.synbox.model.ContainerProvider;
import de.synbox.model.Document;
import de.synbox.model.Organization;
import de.synbox.model.ScheduleModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.synbox.invoker.JSON;

/**
 * CloudServerModel
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-11T22:21:03.947163840Z[Etc/UTC]", comments = "Generator version: 7.22.0-SNAPSHOT")
public class CloudServerModel {
  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @jakarta.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  @jakarta.annotation.Nullable
  private String metrics;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  @jakarta.annotation.Nullable
  private String start;

  public static final String SERIALIZED_NAME_STOP = "stop";
  @SerializedName(SERIALIZED_NAME_STOP)
  @jakarta.annotation.Nullable
  private String stop;

  public static final String SERIALIZED_NAME_ENABLE_AUTO_POWER_CONTROL = "enableAutoPowerControl";
  @SerializedName(SERIALIZED_NAME_ENABLE_AUTO_POWER_CONTROL)
  @jakarta.annotation.Nullable
  private Boolean enableAutoPowerControl;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @jakarta.annotation.Nullable
  private String owner;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @jakarta.annotation.Nullable
  private String displayName;

  public static final String SERIALIZED_NAME_IP = "ip";
  @SerializedName(SERIALIZED_NAME_IP)
  @jakarta.annotation.Nullable
  private String ip;

  public static final String SERIALIZED_NAME_SUSPENDED = "suspended";
  @SerializedName(SERIALIZED_NAME_SUSPENDED)
  @jakarta.annotation.Nullable
  private String suspended;

  public static final String SERIALIZED_NAME_CPU_TYPE = "cpu_type";
  @SerializedName(SERIALIZED_NAME_CPU_TYPE)
  @jakarta.annotation.Nullable
  private String cpuType;

  /**
   * Gets or Sets powerLevel
   */
  @JsonAdapter(PowerLevelEnum.Adapter.class)
  public enum PowerLevelEnum {
    SMALL_COMPUTE("SMALL_COMPUTE"),
    
    MEDIUM_COMPUTE("MEDIUM_COMPUTE"),
    
    LARGE_COMPUTE("LARGE_COMPUTE"),
    
    HEAVY_COMPUTE("HEAVY_COMPUTE"),
    
    HYTALE_FREE("HYTALE_FREE"),
    
    SMALL_RAM("SMALL_RAM"),
    
    MEDIUM_RAM("MEDIUM_RAM"),
    
    LARGE_RAM("LARGE_RAM"),
    
    SMALL_PREMIUM("SMALL_PREMIUM"),
    
    MEDIUM_PREMIUM("MEDIUM_PREMIUM");

    private String value;

    PowerLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PowerLevelEnum fromValue(String value) {
      for (PowerLevelEnum b : PowerLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PowerLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PowerLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PowerLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PowerLevelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PowerLevelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_POWER_LEVEL = "powerLevel";
  @SerializedName(SERIALIZED_NAME_POWER_LEVEL)
  @jakarta.annotation.Nullable
  private PowerLevelEnum powerLevel;

  public static final String SERIALIZED_NAME_SCHEDULE_MODELS = "scheduleModels";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_MODELS)
  @jakarta.annotation.Nullable
  private List<ScheduleModel> scheduleModels = new ArrayList<>();

  public static final String SERIALIZED_NAME_BACKUPS = "backups";
  @SerializedName(SERIALIZED_NAME_BACKUPS)
  @jakarta.annotation.Nullable
  private List<BackupModel> backups = new ArrayList<>();

  public static final String SERIALIZED_NAME_WATCHING = "watching";
  @SerializedName(SERIALIZED_NAME_WATCHING)
  @jakarta.annotation.Nullable
  private Boolean watching;

  public static final String SERIALIZED_NAME_START_VOLUME = "startVolume";
  @SerializedName(SERIALIZED_NAME_START_VOLUME)
  @jakarta.annotation.Nullable
  private String startVolume;

  public static final String SERIALIZED_NAME_SERVER_ID = "server_id";
  @SerializedName(SERIALIZED_NAME_SERVER_ID)
  @jakarta.annotation.Nullable
  private String serverId;

  public static final String SERIALIZED_NAME_MONEY_POOL_ID = "money_pool_id";
  @SerializedName(SERIALIZED_NAME_MONEY_POOL_ID)
  @jakarta.annotation.Nullable
  private String moneyPoolId;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  @jakarta.annotation.Nullable
  private List<String> volumes = new ArrayList<>();

  public static final String SERIALIZED_NAME_ENVS = "envs";
  @SerializedName(SERIALIZED_NAME_ENVS)
  @jakarta.annotation.Nullable
  private CloudServerModelEnvs envs;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  @jakarta.annotation.Nullable
  private Document permissions;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  @jakarta.annotation.Nullable
  private Integer port;

  public static final String SERIALIZED_NAME_PUBLIC_IP = "publicIp";
  @SerializedName(SERIALIZED_NAME_PUBLIC_IP)
  @jakarta.annotation.Nullable
  private String publicIp;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  @jakarta.annotation.Nullable
  private Organization organization;

  public static final String SERIALIZED_NAME_ONE_TME_PASSWORD = "oneTmePassword";
  @SerializedName(SERIALIZED_NAME_ONE_TME_PASSWORD)
  @jakarta.annotation.Nullable
  private String oneTmePassword;

  public static final String SERIALIZED_NAME_CONTAINER_PROVIDER = "containerProvider";
  @SerializedName(SERIALIZED_NAME_CONTAINER_PROVIDER)
  @jakarta.annotation.Nullable
  private ContainerProvider containerProvider;

  public static final String SERIALIZED_NAME_DELTA_TILL_START = "deltaTillStart";
  @SerializedName(SERIALIZED_NAME_DELTA_TILL_START)
  @jakarta.annotation.Nullable
  private Long deltaTillStart;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @jakarta.annotation.Nullable
  private String accountId;

  public CloudServerModel() {
  }

  public CloudServerModel provider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @jakarta.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public CloudServerModel metrics(@jakarta.annotation.Nullable String metrics) {
    this.metrics = metrics;
    return this;
  }

  /**
   * Get metrics
   * @return metrics
   */
  @jakarta.annotation.Nullable
  public String getMetrics() {
    return metrics;
  }

  public void setMetrics(@jakarta.annotation.Nullable String metrics) {
    this.metrics = metrics;
  }


  public CloudServerModel start(@jakarta.annotation.Nullable String start) {
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  public String getStart() {
    return start;
  }

  public void setStart(@jakarta.annotation.Nullable String start) {
    this.start = start;
  }


  public CloudServerModel stop(@jakarta.annotation.Nullable String stop) {
    this.stop = stop;
    return this;
  }

  /**
   * Get stop
   * @return stop
   */
  @jakarta.annotation.Nullable
  public String getStop() {
    return stop;
  }

  public void setStop(@jakarta.annotation.Nullable String stop) {
    this.stop = stop;
  }


  public CloudServerModel enableAutoPowerControl(@jakarta.annotation.Nullable Boolean enableAutoPowerControl) {
    this.enableAutoPowerControl = enableAutoPowerControl;
    return this;
  }

  /**
   * Get enableAutoPowerControl
   * @return enableAutoPowerControl
   */
  @jakarta.annotation.Nullable
  public Boolean getEnableAutoPowerControl() {
    return enableAutoPowerControl;
  }

  public void setEnableAutoPowerControl(@jakarta.annotation.Nullable Boolean enableAutoPowerControl) {
    this.enableAutoPowerControl = enableAutoPowerControl;
  }


  public CloudServerModel owner(@jakarta.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @jakarta.annotation.Nullable
  public String getOwner() {
    return owner;
  }

  public void setOwner(@jakarta.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public CloudServerModel displayName(@jakarta.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @jakarta.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@jakarta.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public CloudServerModel ip(@jakarta.annotation.Nullable String ip) {
    this.ip = ip;
    return this;
  }

  /**
   * Get ip
   * @return ip
   */
  @jakarta.annotation.Nullable
  public String getIp() {
    return ip;
  }

  public void setIp(@jakarta.annotation.Nullable String ip) {
    this.ip = ip;
  }


  public CloudServerModel suspended(@jakarta.annotation.Nullable String suspended) {
    this.suspended = suspended;
    return this;
  }

  /**
   * Get suspended
   * @return suspended
   */
  @jakarta.annotation.Nullable
  public String getSuspended() {
    return suspended;
  }

  public void setSuspended(@jakarta.annotation.Nullable String suspended) {
    this.suspended = suspended;
  }


  public CloudServerModel cpuType(@jakarta.annotation.Nullable String cpuType) {
    this.cpuType = cpuType;
    return this;
  }

  /**
   * Get cpuType
   * @return cpuType
   */
  @jakarta.annotation.Nullable
  public String getCpuType() {
    return cpuType;
  }

  public void setCpuType(@jakarta.annotation.Nullable String cpuType) {
    this.cpuType = cpuType;
  }


  public CloudServerModel powerLevel(@jakarta.annotation.Nullable PowerLevelEnum powerLevel) {
    this.powerLevel = powerLevel;
    return this;
  }

  /**
   * Get powerLevel
   * @return powerLevel
   */
  @jakarta.annotation.Nullable
  public PowerLevelEnum getPowerLevel() {
    return powerLevel;
  }

  public void setPowerLevel(@jakarta.annotation.Nullable PowerLevelEnum powerLevel) {
    this.powerLevel = powerLevel;
  }


  public CloudServerModel scheduleModels(@jakarta.annotation.Nullable List<ScheduleModel> scheduleModels) {
    this.scheduleModels = scheduleModels;
    return this;
  }

  public CloudServerModel addScheduleModelsItem(ScheduleModel scheduleModelsItem) {
    if (this.scheduleModels == null) {
      this.scheduleModels = new ArrayList<>();
    }
    this.scheduleModels.add(scheduleModelsItem);
    return this;
  }

  /**
   * Get scheduleModels
   * @return scheduleModels
   */
  @jakarta.annotation.Nullable
  public List<ScheduleModel> getScheduleModels() {
    return scheduleModels;
  }

  public void setScheduleModels(@jakarta.annotation.Nullable List<ScheduleModel> scheduleModels) {
    this.scheduleModels = scheduleModels;
  }


  public CloudServerModel backups(@jakarta.annotation.Nullable List<BackupModel> backups) {
    this.backups = backups;
    return this;
  }

  public CloudServerModel addBackupsItem(BackupModel backupsItem) {
    if (this.backups == null) {
      this.backups = new ArrayList<>();
    }
    this.backups.add(backupsItem);
    return this;
  }

  /**
   * Get backups
   * @return backups
   */
  @jakarta.annotation.Nullable
  public List<BackupModel> getBackups() {
    return backups;
  }

  public void setBackups(@jakarta.annotation.Nullable List<BackupModel> backups) {
    this.backups = backups;
  }


  public CloudServerModel watching(@jakarta.annotation.Nullable Boolean watching) {
    this.watching = watching;
    return this;
  }

  /**
   * Get watching
   * @return watching
   */
  @jakarta.annotation.Nullable
  public Boolean getWatching() {
    return watching;
  }

  public void setWatching(@jakarta.annotation.Nullable Boolean watching) {
    this.watching = watching;
  }


  public CloudServerModel startVolume(@jakarta.annotation.Nullable String startVolume) {
    this.startVolume = startVolume;
    return this;
  }

  /**
   * Get startVolume
   * @return startVolume
   */
  @jakarta.annotation.Nullable
  public String getStartVolume() {
    return startVolume;
  }

  public void setStartVolume(@jakarta.annotation.Nullable String startVolume) {
    this.startVolume = startVolume;
  }


  public CloudServerModel serverId(@jakarta.annotation.Nullable String serverId) {
    this.serverId = serverId;
    return this;
  }

  /**
   * Get serverId
   * @return serverId
   */
  @jakarta.annotation.Nullable
  public String getServerId() {
    return serverId;
  }

  public void setServerId(@jakarta.annotation.Nullable String serverId) {
    this.serverId = serverId;
  }


  public CloudServerModel moneyPoolId(@jakarta.annotation.Nullable String moneyPoolId) {
    this.moneyPoolId = moneyPoolId;
    return this;
  }

  /**
   * Get moneyPoolId
   * @return moneyPoolId
   */
  @jakarta.annotation.Nullable
  public String getMoneyPoolId() {
    return moneyPoolId;
  }

  public void setMoneyPoolId(@jakarta.annotation.Nullable String moneyPoolId) {
    this.moneyPoolId = moneyPoolId;
  }


  public CloudServerModel volumes(@jakarta.annotation.Nullable List<String> volumes) {
    this.volumes = volumes;
    return this;
  }

  public CloudServerModel addVolumesItem(String volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

  /**
   * Get volumes
   * @return volumes
   */
  @jakarta.annotation.Nullable
  public List<String> getVolumes() {
    return volumes;
  }

  public void setVolumes(@jakarta.annotation.Nullable List<String> volumes) {
    this.volumes = volumes;
  }


  public CloudServerModel envs(@jakarta.annotation.Nullable CloudServerModelEnvs envs) {
    this.envs = envs;
    return this;
  }

  /**
   * Get envs
   * @return envs
   */
  @jakarta.annotation.Nullable
  public CloudServerModelEnvs getEnvs() {
    return envs;
  }

  public void setEnvs(@jakarta.annotation.Nullable CloudServerModelEnvs envs) {
    this.envs = envs;
  }


  public CloudServerModel permissions(@jakarta.annotation.Nullable Document permissions) {
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nullable
  public Document getPermissions() {
    return permissions;
  }

  public void setPermissions(@jakarta.annotation.Nullable Document permissions) {
    this.permissions = permissions;
  }


  public CloudServerModel port(@jakarta.annotation.Nullable Integer port) {
    this.port = port;
    return this;
  }

  /**
   * Get port
   * @return port
   */
  @jakarta.annotation.Nullable
  public Integer getPort() {
    return port;
  }

  public void setPort(@jakarta.annotation.Nullable Integer port) {
    this.port = port;
  }


  public CloudServerModel publicIp(@jakarta.annotation.Nullable String publicIp) {
    this.publicIp = publicIp;
    return this;
  }

  /**
   * Get publicIp
   * @return publicIp
   */
  @jakarta.annotation.Nullable
  public String getPublicIp() {
    return publicIp;
  }

  public void setPublicIp(@jakarta.annotation.Nullable String publicIp) {
    this.publicIp = publicIp;
  }


  public CloudServerModel organization(@jakarta.annotation.Nullable Organization organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get organization
   * @return organization
   */
  @jakarta.annotation.Nullable
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(@jakarta.annotation.Nullable Organization organization) {
    this.organization = organization;
  }


  public CloudServerModel oneTmePassword(@jakarta.annotation.Nullable String oneTmePassword) {
    this.oneTmePassword = oneTmePassword;
    return this;
  }

  /**
   * Get oneTmePassword
   * @return oneTmePassword
   */
  @jakarta.annotation.Nullable
  public String getOneTmePassword() {
    return oneTmePassword;
  }

  public void setOneTmePassword(@jakarta.annotation.Nullable String oneTmePassword) {
    this.oneTmePassword = oneTmePassword;
  }


  public CloudServerModel containerProvider(@jakarta.annotation.Nullable ContainerProvider containerProvider) {
    this.containerProvider = containerProvider;
    return this;
  }

  /**
   * Get containerProvider
   * @return containerProvider
   */
  @jakarta.annotation.Nullable
  public ContainerProvider getContainerProvider() {
    return containerProvider;
  }

  public void setContainerProvider(@jakarta.annotation.Nullable ContainerProvider containerProvider) {
    this.containerProvider = containerProvider;
  }


  public CloudServerModel deltaTillStart(@jakarta.annotation.Nullable Long deltaTillStart) {
    this.deltaTillStart = deltaTillStart;
    return this;
  }

  /**
   * Get deltaTillStart
   * @return deltaTillStart
   */
  @jakarta.annotation.Nullable
  public Long getDeltaTillStart() {
    return deltaTillStart;
  }

  public void setDeltaTillStart(@jakarta.annotation.Nullable Long deltaTillStart) {
    this.deltaTillStart = deltaTillStart;
  }


  public CloudServerModel accountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @jakarta.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudServerModel cloudServerModel = (CloudServerModel) o;
    return Objects.equals(this.provider, cloudServerModel.provider) &&
        Objects.equals(this.metrics, cloudServerModel.metrics) &&
        Objects.equals(this.start, cloudServerModel.start) &&
        Objects.equals(this.stop, cloudServerModel.stop) &&
        Objects.equals(this.enableAutoPowerControl, cloudServerModel.enableAutoPowerControl) &&
        Objects.equals(this.owner, cloudServerModel.owner) &&
        Objects.equals(this.displayName, cloudServerModel.displayName) &&
        Objects.equals(this.ip, cloudServerModel.ip) &&
        Objects.equals(this.suspended, cloudServerModel.suspended) &&
        Objects.equals(this.cpuType, cloudServerModel.cpuType) &&
        Objects.equals(this.powerLevel, cloudServerModel.powerLevel) &&
        Objects.equals(this.scheduleModels, cloudServerModel.scheduleModels) &&
        Objects.equals(this.backups, cloudServerModel.backups) &&
        Objects.equals(this.watching, cloudServerModel.watching) &&
        Objects.equals(this.startVolume, cloudServerModel.startVolume) &&
        Objects.equals(this.serverId, cloudServerModel.serverId) &&
        Objects.equals(this.moneyPoolId, cloudServerModel.moneyPoolId) &&
        Objects.equals(this.volumes, cloudServerModel.volumes) &&
        Objects.equals(this.envs, cloudServerModel.envs) &&
        Objects.equals(this.permissions, cloudServerModel.permissions) &&
        Objects.equals(this.port, cloudServerModel.port) &&
        Objects.equals(this.publicIp, cloudServerModel.publicIp) &&
        Objects.equals(this.organization, cloudServerModel.organization) &&
        Objects.equals(this.oneTmePassword, cloudServerModel.oneTmePassword) &&
        Objects.equals(this.containerProvider, cloudServerModel.containerProvider) &&
        Objects.equals(this.deltaTillStart, cloudServerModel.deltaTillStart) &&
        Objects.equals(this.accountId, cloudServerModel.accountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, metrics, start, stop, enableAutoPowerControl, owner, displayName, ip, suspended, cpuType, powerLevel, scheduleModels, backups, watching, startVolume, serverId, moneyPoolId, volumes, envs, permissions, port, publicIp, organization, oneTmePassword, containerProvider, deltaTillStart, accountId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudServerModel {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    enableAutoPowerControl: ").append(toIndentedString(enableAutoPowerControl)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
    sb.append("    cpuType: ").append(toIndentedString(cpuType)).append("\n");
    sb.append("    powerLevel: ").append(toIndentedString(powerLevel)).append("\n");
    sb.append("    scheduleModels: ").append(toIndentedString(scheduleModels)).append("\n");
    sb.append("    backups: ").append(toIndentedString(backups)).append("\n");
    sb.append("    watching: ").append(toIndentedString(watching)).append("\n");
    sb.append("    startVolume: ").append(toIndentedString(startVolume)).append("\n");
    sb.append("    serverId: ").append(toIndentedString(serverId)).append("\n");
    sb.append("    moneyPoolId: ").append(toIndentedString(moneyPoolId)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    envs: ").append(toIndentedString(envs)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    publicIp: ").append(toIndentedString(publicIp)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    oneTmePassword: ").append(toIndentedString(oneTmePassword)).append("\n");
    sb.append("    containerProvider: ").append(toIndentedString(containerProvider)).append("\n");
    sb.append("    deltaTillStart: ").append(toIndentedString(deltaTillStart)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("provider", "metrics", "start", "stop", "enableAutoPowerControl", "owner", "displayName", "ip", "suspended", "cpu_type", "powerLevel", "scheduleModels", "backups", "watching", "startVolume", "server_id", "money_pool_id", "volumes", "envs", "permissions", "port", "publicIp", "organization", "oneTmePassword", "containerProvider", "deltaTillStart", "account_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CloudServerModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CloudServerModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CloudServerModel is not found in the empty JSON string", CloudServerModel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CloudServerModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CloudServerModel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("metrics") != null && !jsonObj.get("metrics").isJsonNull()) && !jsonObj.get("metrics").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `metrics` to be a primitive type in the JSON string but got `%s`", jsonObj.get("metrics").toString()));
      }
      if ((jsonObj.get("start") != null && !jsonObj.get("start").isJsonNull()) && !jsonObj.get("start").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `start` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start").toString()));
      }
      if ((jsonObj.get("stop") != null && !jsonObj.get("stop").isJsonNull()) && !jsonObj.get("stop").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stop` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stop").toString()));
      }
      if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull()) && !jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("ip") != null && !jsonObj.get("ip").isJsonNull()) && !jsonObj.get("ip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ip").toString()));
      }
      if ((jsonObj.get("suspended") != null && !jsonObj.get("suspended").isJsonNull()) && !jsonObj.get("suspended").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `suspended` to be a primitive type in the JSON string but got `%s`", jsonObj.get("suspended").toString()));
      }
      if ((jsonObj.get("cpu_type") != null && !jsonObj.get("cpu_type").isJsonNull()) && !jsonObj.get("cpu_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cpu_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cpu_type").toString()));
      }
      if ((jsonObj.get("powerLevel") != null && !jsonObj.get("powerLevel").isJsonNull()) && !jsonObj.get("powerLevel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `powerLevel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("powerLevel").toString()));
      }
      // validate the optional field `powerLevel`
      if (jsonObj.get("powerLevel") != null && !jsonObj.get("powerLevel").isJsonNull()) {
        PowerLevelEnum.validateJsonElement(jsonObj.get("powerLevel"));
      }
      if (jsonObj.get("scheduleModels") != null && !jsonObj.get("scheduleModels").isJsonNull()) {
        JsonArray jsonArrayscheduleModels = jsonObj.getAsJsonArray("scheduleModels");
        if (jsonArrayscheduleModels != null) {
          // ensure the json data is an array
          if (!jsonObj.get("scheduleModels").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `scheduleModels` to be an array in the JSON string but got `%s`", jsonObj.get("scheduleModels").toString()));
          }

          // validate the optional field `scheduleModels` (array)
          for (int i = 0; i < jsonArrayscheduleModels.size(); i++) {
            ScheduleModel.validateJsonElement(jsonArrayscheduleModels.get(i));
          };
        }
      }
      if (jsonObj.get("backups") != null && !jsonObj.get("backups").isJsonNull()) {
        JsonArray jsonArraybackups = jsonObj.getAsJsonArray("backups");
        if (jsonArraybackups != null) {
          // ensure the json data is an array
          if (!jsonObj.get("backups").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `backups` to be an array in the JSON string but got `%s`", jsonObj.get("backups").toString()));
          }

          // validate the optional field `backups` (array)
          for (int i = 0; i < jsonArraybackups.size(); i++) {
            BackupModel.validateJsonElement(jsonArraybackups.get(i));
          };
        }
      }
      if ((jsonObj.get("startVolume") != null && !jsonObj.get("startVolume").isJsonNull()) && !jsonObj.get("startVolume").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `startVolume` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startVolume").toString()));
      }
      if ((jsonObj.get("server_id") != null && !jsonObj.get("server_id").isJsonNull()) && !jsonObj.get("server_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `server_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("server_id").toString()));
      }
      if ((jsonObj.get("money_pool_id") != null && !jsonObj.get("money_pool_id").isJsonNull()) && !jsonObj.get("money_pool_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `money_pool_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("money_pool_id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("volumes") != null && !jsonObj.get("volumes").isJsonNull() && !jsonObj.get("volumes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `volumes` to be an array in the JSON string but got `%s`", jsonObj.get("volumes").toString()));
      }
      if ((jsonObj.get("publicIp") != null && !jsonObj.get("publicIp").isJsonNull()) && !jsonObj.get("publicIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `publicIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("publicIp").toString()));
      }
      // validate the optional field `organization`
      if (jsonObj.get("organization") != null && !jsonObj.get("organization").isJsonNull()) {
        Organization.validateJsonElement(jsonObj.get("organization"));
      }
      if ((jsonObj.get("oneTmePassword") != null && !jsonObj.get("oneTmePassword").isJsonNull()) && !jsonObj.get("oneTmePassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `oneTmePassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("oneTmePassword").toString()));
      }
      // validate the optional field `containerProvider`
      if (jsonObj.get("containerProvider") != null && !jsonObj.get("containerProvider").isJsonNull()) {
        ContainerProvider.validateJsonElement(jsonObj.get("containerProvider"));
      }
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CloudServerModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CloudServerModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CloudServerModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CloudServerModel.class));

       return (TypeAdapter<T>) new TypeAdapter<CloudServerModel>() {
           @Override
           public void write(JsonWriter out, CloudServerModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CloudServerModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CloudServerModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CloudServerModel
   * @throws IOException if the JSON string is invalid with respect to CloudServerModel
   */
  public static CloudServerModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CloudServerModel.class);
  }

  /**
   * Convert an instance of CloudServerModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

