/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiCallback;
import de.synbox.invoker.ApiClient;
import de.synbox.invoker.ApiException;
import de.synbox.invoker.ApiResponse;
import de.synbox.invoker.Configuration;
import de.synbox.invoker.Pair;
import de.synbox.invoker.ProgressRequestBody;
import de.synbox.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import de.synbox.model.AiServerConfig;
import de.synbox.model.AiServerConfigRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AiServerConfigurationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AiServerConfigurationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AiServerConfigurationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createConfig
     * @param aiServerConfigRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration successfully extracted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request text is empty or too long </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication is required </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The model did not return a valid configuration </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createConfigCall(@jakarta.annotation.Nonnull AiServerConfigRequest aiServerConfigRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = aiServerConfigRequest;

        // create path and map variables
        String localVarPath = "/api/server/ai/config";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createConfigValidateBeforeCall(@jakarta.annotation.Nonnull AiServerConfigRequest aiServerConfigRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'aiServerConfigRequest' is set
        if (aiServerConfigRequest == null) {
            throw new ApiException("Missing the required parameter 'aiServerConfigRequest' when calling createConfig(Async)");
        }

        return createConfigCall(aiServerConfigRequest, _callback);

    }

    /**
     * Create an AI server configuration
     * Extracts a strictly typed server configuration from untrusted natural-language input.
     * @param aiServerConfigRequest  (required)
     * @return AiServerConfig
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration successfully extracted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request text is empty or too long </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication is required </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The model did not return a valid configuration </td><td>  -  </td></tr>
     </table>
     */
    public AiServerConfig createConfig(@jakarta.annotation.Nonnull AiServerConfigRequest aiServerConfigRequest) throws ApiException {
        ApiResponse<AiServerConfig> localVarResp = createConfigWithHttpInfo(aiServerConfigRequest);
        return localVarResp.getData();
    }

    /**
     * Create an AI server configuration
     * Extracts a strictly typed server configuration from untrusted natural-language input.
     * @param aiServerConfigRequest  (required)
     * @return ApiResponse&lt;AiServerConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration successfully extracted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request text is empty or too long </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication is required </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The model did not return a valid configuration </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AiServerConfig> createConfigWithHttpInfo(@jakarta.annotation.Nonnull AiServerConfigRequest aiServerConfigRequest) throws ApiException {
        okhttp3.Call localVarCall = createConfigValidateBeforeCall(aiServerConfigRequest, null);
        Type localVarReturnType = new TypeToken<AiServerConfig>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create an AI server configuration (asynchronously)
     * Extracts a strictly typed server configuration from untrusted natural-language input.
     * @param aiServerConfigRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration successfully extracted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request text is empty or too long </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication is required </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The model did not return a valid configuration </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createConfigAsync(@jakarta.annotation.Nonnull AiServerConfigRequest aiServerConfigRequest, final ApiCallback<AiServerConfig> _callback) throws ApiException {

        okhttp3.Call localVarCall = createConfigValidateBeforeCall(aiServerConfigRequest, _callback);
        Type localVarReturnType = new TypeToken<AiServerConfig>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
