/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiCallback;
import de.synbox.invoker.ApiClient;
import de.synbox.invoker.ApiException;
import de.synbox.invoker.ApiResponse;
import de.synbox.invoker.Configuration;
import de.synbox.invoker.Pair;
import de.synbox.invoker.ProgressRequestBody;
import de.synbox.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import de.synbox.model.BaseDTO;
import de.synbox.model.MagicLinkRequestDTO;
import de.synbox.model.OrganizationAddMemberDTO;
import de.synbox.model.OrganizationMemberDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addMember
     * @param id ID der Organisation (required)
     * @param organizationAddMemberDTO Mitgliedsdaten (E-Mail, optionale Rolle) (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglied erfolgreich hinzugefuegt </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler beim Weiterleiten der Anfrage </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addMemberCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull OrganizationAddMemberDTO organizationAddMemberDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = organizationAddMemberDTO;

        // create path and map variables
        String localVarPath = "/api/organization/{id}/members"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addMemberValidateBeforeCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull OrganizationAddMemberDTO organizationAddMemberDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling addMember(Async)");
        }

        // verify the required parameter 'organizationAddMemberDTO' is set
        if (organizationAddMemberDTO == null) {
            throw new ApiException("Missing the required parameter 'organizationAddMemberDTO' when calling addMember(Async)");
        }

        return addMemberCall(id, organizationAddMemberDTO, _callback);

    }

    /**
     * Mitglied zur Organisation hinzufuegen
     * Fuegt ein Mitglied anhand von E-Mail und optionaler Rolle zur angegebenen Organisation hinzu. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param organizationAddMemberDTO Mitgliedsdaten (E-Mail, optionale Rolle) (required)
     * @return OrganizationMemberDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglied erfolgreich hinzugefuegt </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler beim Weiterleiten der Anfrage </td><td>  -  </td></tr>
     </table>
     */
    public OrganizationMemberDTO addMember(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull OrganizationAddMemberDTO organizationAddMemberDTO) throws ApiException {
        ApiResponse<OrganizationMemberDTO> localVarResp = addMemberWithHttpInfo(id, organizationAddMemberDTO);
        return localVarResp.getData();
    }

    /**
     * Mitglied zur Organisation hinzufuegen
     * Fuegt ein Mitglied anhand von E-Mail und optionaler Rolle zur angegebenen Organisation hinzu. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param organizationAddMemberDTO Mitgliedsdaten (E-Mail, optionale Rolle) (required)
     * @return ApiResponse&lt;OrganizationMemberDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglied erfolgreich hinzugefuegt </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler beim Weiterleiten der Anfrage </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganizationMemberDTO> addMemberWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull OrganizationAddMemberDTO organizationAddMemberDTO) throws ApiException {
        okhttp3.Call localVarCall = addMemberValidateBeforeCall(id, organizationAddMemberDTO, null);
        Type localVarReturnType = new TypeToken<OrganizationMemberDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Mitglied zur Organisation hinzufuegen (asynchronously)
     * Fuegt ein Mitglied anhand von E-Mail und optionaler Rolle zur angegebenen Organisation hinzu. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param organizationAddMemberDTO Mitgliedsdaten (E-Mail, optionale Rolle) (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglied erfolgreich hinzugefuegt </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler beim Weiterleiten der Anfrage </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addMemberAsync(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull OrganizationAddMemberDTO organizationAddMemberDTO, final ApiCallback<OrganizationMemberDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = addMemberValidateBeforeCall(id, organizationAddMemberDTO, _callback);
        Type localVarReturnType = new TypeToken<OrganizationMemberDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listMembers
     * @param id ID der Organisation (required)
     * @param email Optionale exakte Filterung nach E-Mail-Adresse (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglieder erfolgreich geladen </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMembersCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String email, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/organization/{id}/members"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (email != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("email", email));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listMembersValidateBeforeCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String email, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling listMembers(Async)");
        }

        return listMembersCall(id, email, _callback);

    }

    /**
     * Mitglieder einer Organisation auflisten
     * Liefert alle Mitglieder der angegebenen Organisation. Optional kann nach E-Mail gefiltert werden. Nur Admins oder Owner dürfen diese Aktion ausführen.
     * @param id ID der Organisation (required)
     * @param email Optionale exakte Filterung nach E-Mail-Adresse (optional)
     * @return List&lt;OrganizationMemberDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglieder erfolgreich geladen </td><td>  -  </td></tr>
     </table>
     */
    public List<OrganizationMemberDTO> listMembers(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String email) throws ApiException {
        ApiResponse<List<OrganizationMemberDTO>> localVarResp = listMembersWithHttpInfo(id, email);
        return localVarResp.getData();
    }

    /**
     * Mitglieder einer Organisation auflisten
     * Liefert alle Mitglieder der angegebenen Organisation. Optional kann nach E-Mail gefiltert werden. Nur Admins oder Owner dürfen diese Aktion ausführen.
     * @param id ID der Organisation (required)
     * @param email Optionale exakte Filterung nach E-Mail-Adresse (optional)
     * @return ApiResponse&lt;List&lt;OrganizationMemberDTO&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglieder erfolgreich geladen </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<OrganizationMemberDTO>> listMembersWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String email) throws ApiException {
        okhttp3.Call localVarCall = listMembersValidateBeforeCall(id, email, null);
        Type localVarReturnType = new TypeToken<List<OrganizationMemberDTO>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Mitglieder einer Organisation auflisten (asynchronously)
     * Liefert alle Mitglieder der angegebenen Organisation. Optional kann nach E-Mail gefiltert werden. Nur Admins oder Owner dürfen diese Aktion ausführen.
     * @param id ID der Organisation (required)
     * @param email Optionale exakte Filterung nach E-Mail-Adresse (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Mitglieder erfolgreich geladen </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMembersAsync(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String email, final ApiCallback<List<OrganizationMemberDTO>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listMembersValidateBeforeCall(id, email, _callback);
        Type localVarReturnType = new TypeToken<List<OrganizationMemberDTO>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for requestMagicLink
     * @param id ID der Organisation (required)
     * @param magicLinkRequestDTO Email und CallbackUrl. Die callbackUrl erhält JSON mit dem magicLink. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler oder Fehler beim Weiterleiten an SynBox </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Magic-Link erfolgreich angefordert </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage (z.B. fehlende/ungueltige E-Mail) </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call requestMagicLinkCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MagicLinkRequestDTO magicLinkRequestDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = magicLinkRequestDTO;

        // create path and map variables
        String localVarPath = "/api/organization/{id}/members/magiclink"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call requestMagicLinkValidateBeforeCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MagicLinkRequestDTO magicLinkRequestDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling requestMagicLink(Async)");
        }

        // verify the required parameter 'magicLinkRequestDTO' is set
        if (magicLinkRequestDTO == null) {
            throw new ApiException("Missing the required parameter 'magicLinkRequestDTO' when calling requestMagicLink(Async)");
        }

        return requestMagicLinkCall(id, magicLinkRequestDTO, _callback);

    }

    /**
     * Magic-Link fuer ein Organisations-Mitglied anfordern
     * Fordert fuer die angegebene E-Mail-Adresse einen Magic-Link (Token-Login) bei SynBox an. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param magicLinkRequestDTO Email und CallbackUrl. Die callbackUrl erhält JSON mit dem magicLink. (required)
     * @return BaseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler oder Fehler beim Weiterleiten an SynBox </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Magic-Link erfolgreich angefordert </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage (z.B. fehlende/ungueltige E-Mail) </td><td>  -  </td></tr>
     </table>
     */
    public BaseDTO requestMagicLink(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MagicLinkRequestDTO magicLinkRequestDTO) throws ApiException {
        ApiResponse<BaseDTO> localVarResp = requestMagicLinkWithHttpInfo(id, magicLinkRequestDTO);
        return localVarResp.getData();
    }

    /**
     * Magic-Link fuer ein Organisations-Mitglied anfordern
     * Fordert fuer die angegebene E-Mail-Adresse einen Magic-Link (Token-Login) bei SynBox an. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param magicLinkRequestDTO Email und CallbackUrl. Die callbackUrl erhält JSON mit dem magicLink. (required)
     * @return ApiResponse&lt;BaseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler oder Fehler beim Weiterleiten an SynBox </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Magic-Link erfolgreich angefordert </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage (z.B. fehlende/ungueltige E-Mail) </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseDTO> requestMagicLinkWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MagicLinkRequestDTO magicLinkRequestDTO) throws ApiException {
        okhttp3.Call localVarCall = requestMagicLinkValidateBeforeCall(id, magicLinkRequestDTO, null);
        Type localVarReturnType = new TypeToken<BaseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Magic-Link fuer ein Organisations-Mitglied anfordern (asynchronously)
     * Fordert fuer die angegebene E-Mail-Adresse einen Magic-Link (Token-Login) bei SynBox an. Nur admin/owner duerfen diese Aktion ausfuehren.
     * @param id ID der Organisation (required)
     * @param magicLinkRequestDTO Email und CallbackUrl. Die callbackUrl erhält JSON mit dem magicLink. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 403 </td><td> Keine Berechtigung </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Interner Fehler oder Fehler beim Weiterleiten an SynBox </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Magic-Link erfolgreich angefordert </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Ungueltige Anfrage (z.B. fehlende/ungueltige E-Mail) </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call requestMagicLinkAsync(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MagicLinkRequestDTO magicLinkRequestDTO, final ApiCallback<BaseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = requestMagicLinkValidateBeforeCall(id, magicLinkRequestDTO, _callback);
        Type localVarReturnType = new TypeToken<BaseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
