/*
 * Synbox-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.synbox.api;

import de.synbox.invoker.ApiCallback;
import de.synbox.invoker.ApiClient;
import de.synbox.invoker.ApiException;
import de.synbox.invoker.ApiResponse;
import de.synbox.invoker.Configuration;
import de.synbox.invoker.Pair;
import de.synbox.invoker.ProgressRequestBody;
import de.synbox.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import de.synbox.model.PveQemuRrdDataPoint;
import de.synbox.model.VPSModel;
import de.synbox.model.VPSVncConsole;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VpsManagementApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public VpsManagementApi() {
        this(Configuration.getDefaultApiClient());
    }

    public VpsManagementApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for extendVps
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> VPS extended successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid VPS ID, invalid price or hourly VPS </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Not enough tokens </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> VPS not found or not owned by the caller </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> VPS changed during extension; please retry </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call extendVpsCall(@jakarta.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/vps/{id}/extend"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call extendVpsValidateBeforeCall(@jakarta.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling extendVps(Async)");
        }

        return extendVpsCall(id, _callback);

    }

    /**
     * Extend own VPS using tokens
     * Extends a VPS by 30 days for its configured price in EUR multiplied by 200 tokens. Returns the updated VPS. Only the owner can extend it. Returns 400 for hourly VPS instances, 402 for insufficient tokens and 404 if the VPS is not owned by the caller.
     * @param id  (required)
     * @return VPSModel
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> VPS extended successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid VPS ID, invalid price or hourly VPS </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Not enough tokens </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> VPS not found or not owned by the caller </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> VPS changed during extension; please retry </td><td>  -  </td></tr>
     </table>
     */
    public VPSModel extendVps(@jakarta.annotation.Nonnull String id) throws ApiException {
        ApiResponse<VPSModel> localVarResp = extendVpsWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Extend own VPS using tokens
     * Extends a VPS by 30 days for its configured price in EUR multiplied by 200 tokens. Returns the updated VPS. Only the owner can extend it. Returns 400 for hourly VPS instances, 402 for insufficient tokens and 404 if the VPS is not owned by the caller.
     * @param id  (required)
     * @return ApiResponse&lt;VPSModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> VPS extended successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid VPS ID, invalid price or hourly VPS </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Not enough tokens </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> VPS not found or not owned by the caller </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> VPS changed during extension; please retry </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VPSModel> extendVpsWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = extendVpsValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<VPSModel>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Extend own VPS using tokens (asynchronously)
     * Extends a VPS by 30 days for its configured price in EUR multiplied by 200 tokens. Returns the updated VPS. Only the owner can extend it. Returns 400 for hourly VPS instances, 402 for insufficient tokens and 404 if the VPS is not owned by the caller.
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> VPS extended successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid VPS ID, invalid price or hourly VPS </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Not enough tokens </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> VPS not found or not owned by the caller </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> VPS changed during extension; please retry </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call extendVpsAsync(@jakarta.annotation.Nonnull String id, final ApiCallback<VPSModel> _callback) throws ApiException {

        okhttp3.Call localVarCall = extendVpsValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<VPSModel>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getMetrics
     * @param id  (required)
     * @param timeframe  (optional, default to hour)
     * @param cf  (optional, default to AVERAGE)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMetricsCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String timeframe, @jakarta.annotation.Nullable String cf, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/vps/{id}/metrics"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (timeframe != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timeframe", timeframe));
        }

        if (cf != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cf", cf));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMetricsValidateBeforeCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String timeframe, @jakarta.annotation.Nullable String cf, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getMetrics(Async)");
        }

        return getMetricsCall(id, timeframe, cf, _callback);

    }

    /**
     * VPS RRD metrics
     * Returns Proxmox rrddata. Timeframe: hour, day, week, month or year. Consolidation function: AVERAGE or MAX. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param timeframe  (optional, default to hour)
     * @param cf  (optional, default to AVERAGE)
     * @return List&lt;PveQemuRrdDataPoint&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<PveQemuRrdDataPoint> getMetrics(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String timeframe, @jakarta.annotation.Nullable String cf) throws ApiException {
        ApiResponse<List<PveQemuRrdDataPoint>> localVarResp = getMetricsWithHttpInfo(id, timeframe, cf);
        return localVarResp.getData();
    }

    /**
     * VPS RRD metrics
     * Returns Proxmox rrddata. Timeframe: hour, day, week, month or year. Consolidation function: AVERAGE or MAX. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param timeframe  (optional, default to hour)
     * @param cf  (optional, default to AVERAGE)
     * @return ApiResponse&lt;List&lt;PveQemuRrdDataPoint&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<PveQemuRrdDataPoint>> getMetricsWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String timeframe, @jakarta.annotation.Nullable String cf) throws ApiException {
        okhttp3.Call localVarCall = getMetricsValidateBeforeCall(id, timeframe, cf, null);
        Type localVarReturnType = new TypeToken<List<PveQemuRrdDataPoint>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * VPS RRD metrics (asynchronously)
     * Returns Proxmox rrddata. Timeframe: hour, day, week, month or year. Consolidation function: AVERAGE or MAX. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param timeframe  (optional, default to hour)
     * @param cf  (optional, default to AVERAGE)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMetricsAsync(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable String timeframe, @jakarta.annotation.Nullable String cf, final ApiCallback<List<PveQemuRrdDataPoint>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMetricsValidateBeforeCall(id, timeframe, cf, _callback);
        Type localVarReturnType = new TypeToken<List<PveQemuRrdDataPoint>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getVpsInstances
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVpsInstancesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/vps";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getVpsInstancesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getVpsInstancesCall(_callback);

    }

    /**
     * List own VPS instances
     * 
     * @return List&lt;VPSModel&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<VPSModel> getVpsInstances() throws ApiException {
        ApiResponse<List<VPSModel>> localVarResp = getVpsInstancesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List own VPS instances
     * 
     * @return ApiResponse&lt;List&lt;VPSModel&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<VPSModel>> getVpsInstancesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getVpsInstancesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<VPSModel>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List own VPS instances (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVpsInstancesAsync(final ApiCallback<List<VPSModel>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getVpsInstancesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<VPSModel>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for powerAction
     * @param id  (required)
     * @param aktion  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call powerActionCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull String aktion, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/vps/{id}/{aktion}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "aktion" + "}", localVarApiClient.escapeString(aktion.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call powerActionValidateBeforeCall(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull String aktion, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling powerAction(Async)");
        }

        // verify the required parameter 'aktion' is set
        if (aktion == null) {
            throw new ApiException("Missing the required parameter 'aktion' when calling powerAction(Async)");
        }

        return powerActionCall(id, aktion, _callback);

    }

    /**
     * VPS power action
     * Starts, gracefully stops, kills or reboots a VPS. Returns 202 when Proxmox accepts the task. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param aktion  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void powerAction(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull String aktion) throws ApiException {
        powerActionWithHttpInfo(id, aktion);
    }

    /**
     * VPS power action
     * Starts, gracefully stops, kills or reboots a VPS. Returns 202 when Proxmox accepts the task. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param aktion  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> powerActionWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull String aktion) throws ApiException {
        okhttp3.Call localVarCall = powerActionValidateBeforeCall(id, aktion, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * VPS power action (asynchronously)
     * Starts, gracefully stops, kills or reboots a VPS. Returns 202 when Proxmox accepts the task. The ID is the VPS MongoDB ObjectId as a 24-character hexadecimal string.
     * @param id  (required)
     * @param aktion  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call powerActionAsync(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull String aktion, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = powerActionValidateBeforeCall(id, aktion, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for vncConsole
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call vncConsoleCall(@jakarta.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/vps/{id}/vnc-console"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call vncConsoleValidateBeforeCall(@jakarta.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling vncConsole(Async)");
        }

        return vncConsoleCall(id, _callback);

    }

    /**
     * Get VPS VNC console URL
     * Returns the backend WebSocket path. Connect directly using noVNC wsProtocols [&#39;binary&#39;, &#39;synbox-auth.&#39; + accessToken]. Proxmox credentials remain in the backend. This helper endpoint is optional.
     * @param id  (required)
     * @return VPSVncConsole
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public VPSVncConsole vncConsole(@jakarta.annotation.Nonnull String id) throws ApiException {
        ApiResponse<VPSVncConsole> localVarResp = vncConsoleWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get VPS VNC console URL
     * Returns the backend WebSocket path. Connect directly using noVNC wsProtocols [&#39;binary&#39;, &#39;synbox-auth.&#39; + accessToken]. Proxmox credentials remain in the backend. This helper endpoint is optional.
     * @param id  (required)
     * @return ApiResponse&lt;VPSVncConsole&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VPSVncConsole> vncConsoleWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = vncConsoleValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<VPSVncConsole>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get VPS VNC console URL (asynchronously)
     * Returns the backend WebSocket path. Connect directly using noVNC wsProtocols [&#39;binary&#39;, &#39;synbox-auth.&#39; + accessToken]. Proxmox credentials remain in the backend. This helper endpoint is optional.
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call vncConsoleAsync(@jakarta.annotation.Nonnull String id, final ApiCallback<VPSVncConsole> _callback) throws ApiException {

        okhttp3.Call localVarCall = vncConsoleValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<VPSVncConsole>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
